"""09_new_fields

Revision ID: 144a19ec473e
Revises: 6ec94e648b44
Create Date: 2023-11-16 09:24:23.723640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144a19ec473e'
down_revision: Union[str, None] = '6ec94e648b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('timestamp', sa.TIMESTAMP(), nullable=True))
    op.add_column('orders', sa.Column('atr', sa.Numeric(precision=10, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'atr')
    op.drop_column('orders', 'timestamp')
    # ### end Alembic commands ###
