"""02_ema_constraint_correction

Revision ID: 3d048ed7a869
Revises: d6f2db3fa9e2
Create Date: 2023-11-06 16:22:31.725096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d048ed7a869'
down_revision: Union[str, None] = 'd6f2db3fa9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_ema', 'ema', type_='unique')
    op.create_unique_constraint('unique_ema', 'ema', ['ticker_id', 'interval', 'timestamp_column', 'span'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_ema', 'ema', type_='unique')
    op.create_unique_constraint('unique_ema', 'ema', ['ticker_id', 'interval', 'timestamp_column'])
    # ### end Alembic commands ###
