"""08_positions

Revision ID: 6ec94e648b44
Revises: f30557b59093
Create Date: 2023-11-15 19:10:36.884625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec94e648b44'
down_revision: Union[str, None] = 'f30557b59093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.BIGINT(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_account_id', 'timestamp', name='unique_positions_checks')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker_id', sa.BIGINT(), nullable=False),
    sa.Column('task', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task'], ['positions_checks.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.ticker_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'task', name='unique_positions')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_table('positions_checks')
    # ### end Alembic commands ###
