"""11_realtions_deal

Revision ID: 80bff8119e8e
Revises: 6d7c1c5690f6
Create Date: 2023-11-20 14:21:55.127230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bff8119e8e'
down_revision: Union[str, None] = '6d7c1c5690f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ticker_id_buy', 'deals', ['ticker_id', 'buy_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticker_id_buy', 'deals', type_='unique')
    # ### end Alembic commands ###
