"""05_accountid

Revision ID: 945d23f0b68c
Revises: bf3e392f91dc
Create Date: 2023-11-12 11:19:25.085539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945d23f0b68c'
down_revision: Union[str, None] = 'bf3e392f91dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('accountId', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'accountId')
    # ### end Alembic commands ###
