"""06_nullbale_false

Revision ID: 992323241b34
Revises: 945d23f0b68c
Create Date: 2023-11-12 11:21:34.697408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992323241b34'
down_revision: Union[str, None] = '945d23f0b68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'accountId',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('tickers', 'lot',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickers', 'lot',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'accountId',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
