"""03_broker_account

Revision ID: 9ab2d2294265
Revises: 3d048ed7a869
Create Date: 2023-11-08 16:15:56.197198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab2d2294265'
down_revision: Union[str, None] = '3d048ed7a869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_account',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('broker_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'user_id', name='unique_broker_account')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_account')
    # ### end Alembic commands ###
