"""03_lot_and_order

Revision ID: bf3e392f91dc
Revises: 9ab2d2294265
Create Date: 2023-11-11 17:59:24.084067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3e392f91dc'
down_revision: Union[str, None] = '9ab2d2294265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orderId', sa.UUID(), nullable=False),
    sa.Column('executionReportStatus', sa.String(), nullable=False),
    sa.Column('lotsRequested', sa.Integer(), nullable=False),
    sa.Column('lotsExecuted', sa.Integer(), nullable=False),
    sa.Column('initialOrderPrice', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('executedOrderPrice', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('totalOrderAmount', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('initialCommission', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('executedCommission', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('figi', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('initialSecurityPrice', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('orderType', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('instrumentUid', sa.UUID(), nullable=False),
    sa.Column('orderRequestId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orderId', name='unique_orderIdt')
    )
    op.add_column('tickers', sa.Column('lot', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickers', 'lot')
    op.drop_table('orders')
    # ### end Alembic commands ###
