"""01_initial-db

Revision ID: d6f2db3fa9e2
Revises: 
Create Date: 2023-11-06 09:56:08.577991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6f2db3fa9e2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ema_to_calc',
    sa.Column('ema_to_calc_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('interval', sa.String(length=64), nullable=False),
    sa.Column('span', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ema_to_calc_id')
    )
    op.create_table('strategies',
    sa.Column('strategy_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.create_table('tickers',
    sa.Column('ticker_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('figi', sa.String(length=64), nullable=True),
    sa.Column('classcode', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('disable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('ticker_id'),
    sa.UniqueConstraint('name', name='unique_ticker_name')
    )
    op.create_table('timeframes',
    sa.Column('timeframe_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('timeframe_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('lang', sa.String(length=20), nullable=True),
    sa.Column('disable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('candles',
    sa.Column('candl_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.BIGINT(), nullable=False),
    sa.Column('interval', sa.String(length=64), nullable=False),
    sa.Column('timestamp_column', sa.TIMESTAMP(), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.ticker_id'], ),
    sa.PrimaryKeyConstraint('candl_id'),
    sa.UniqueConstraint('ticker_id', 'interval', 'timestamp_column', name='unique_candle')
    )
    op.create_table('ema',
    sa.Column('ema_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.BIGINT(), nullable=False),
    sa.Column('interval', sa.String(length=64), nullable=False),
    sa.Column('span', sa.Integer(), nullable=False),
    sa.Column('timestamp_column', sa.TIMESTAMP(), nullable=False),
    sa.Column('ema', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('atr', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.ticker_id'], ),
    sa.PrimaryKeyConstraint('ema_id'),
    sa.UniqueConstraint('ticker_id', 'interval', 'timestamp_column', name='unique_ema')
    )
    op.create_table('ema_cross',
    sa.Column('ema_cross_id', sa.BIGINT(), nullable=False),
    sa.Column('ticker_id', sa.BIGINT(), nullable=False),
    sa.Column('interval', sa.String(length=64), nullable=False),
    sa.Column('span', sa.Integer(), nullable=False),
    sa.Column('timestamp_column', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.ticker_id'], ),
    sa.PrimaryKeyConstraint('ema_cross_id'),
    sa.UniqueConstraint('ticker_id', 'interval', 'span', 'timestamp_column', name='unique_ema_cross_combination')
    )
    op.create_table('user_strategies',
    sa.Column('user_strategy_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('strategy_id', sa.BIGINT(), nullable=False),
    sa.Column('timeframe_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.timeframe_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_strategy_id'),
    sa.UniqueConstraint('user_id', 'strategy_id', 'timeframe_id', name='unique_user_strategy_timeframe')
    )
    op.create_table('user_tickers',
    sa.Column('user_ticker_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('ticker_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.ticker_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_ticker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tickers')
    op.drop_table('user_strategies')
    op.drop_table('ema_cross')
    op.drop_table('ema')
    op.drop_table('candles')
    op.drop_table('users')
    op.drop_table('timeframes')
    op.drop_table('tickers')
    op.drop_table('strategies')
    op.drop_table('ema_to_calc')
    # ### end Alembic commands ###
