"""07_min_price_increment

Revision ID: f30557b59093
Revises: 992323241b34
Create Date: 2023-11-15 14:05:10.565458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30557b59093'
down_revision: Union[str, None] = '992323241b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('min_price_increment', sa.Numeric(precision=10, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickers', 'min_price_increment')
    # ### end Alembic commands ###
